version: 2

commands:
  install:
    description: Install dependencies from NPM
    steps:
      - run: npm install

  test:
    description: Apply linting, perform security check on dependencies and execute tests and generate code coverage
    steps:
      - run: npm test

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - install

  test-node8:
    docker:
      - image: circleci/node:8
    steps:
        - test

  test-node10:
    docker:
      - image: circleci/node:10
    steps:
      - test

  test-node12:
    docker:
      - image: circleci/node:12
    steps:
      - test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-node8:
          requires:
            - build
      - test-node10:
          requires:
            - build
      - test-node12:
          requires:
            - build
