version: 2

jobs:
  node6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: npm install
      - run: npm test
  node8:
    docker:
        - image: circleci/node:8
    steps:
        - checkout
        - run: npm install
        - run: npm test
  node10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test
  node12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - node6
      - node8
      - node10
      - node12
