version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install

  test-node8:
    docker:
      - image: circleci/node:8
    steps:
        - run: npm test

  test-node10:
    docker:
      - image: circleci/node:10
    steps:
      - run: npm test

  test-node12:
    docker:
      - image: circleci/node:12
    steps:
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-node8:
          requires:
            - build
      - test-node10:
          requires:
            - build
      - test-node12:
          requires:
            - build
